# Generated by Django 4.0 on 2021-12-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PHTRS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pole',
            new_name='Hole',
        ),
    ]
