# Generated by Django 4.0 on 2021-12-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHTRS', '0002_rename_pole_hole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='street_address',
        ),
        migrations.AddField(
            model_name='hole',
            name='district',
            field=models.CharField(default='NULL', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hole',
            name='street',
            field=models.CharField(default='NULL', max_length=200),
            preserve_default=False,
        ),
    ]
