# Generated by Django 4.0 on 2021-12-16 15:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHTRS', '0003_remove_hole_street_address_hole_district_hole_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('hole', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PHTRS.hole')),
                ('isFixed', models.BooleanField(default=False)),
                ('crews', models.CharField(max_length=200)),
                ('hole_status', models.CharField(default='notRepaired', max_length=50, validators=[django.core.validators.RegexValidator('repairing|repaired|temporaryRepaired|notRepaired', message='status invalid！')])),
                ('equipment', models.CharField(max_length=200)),
            ],
        ),
    ]
