# Generated by Django 4.0 on 2021-12-16 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHTRS', '0004_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='hole_status',
            field=models.CharField(default='notRepaired', max_length=50, validators=[django.core.validators.RegexValidator('^repairing$|^repaired$|^temporaryRepaired$|^notRepaired$', message='status invalid！')]),
        ),
    ]
