# Generated by Django 4.0 on 2021-12-16 16:24

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PHTRS', '0005_alter_state_hole_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='reporter',
            field=models.CharField(default='Name', max_length=100, verbose_name='Reporter Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hole',
            name='hole_location',
            field=models.CharField(max_length=20, verbose_name='Location of the hole'),
        ),
        migrations.AlterField(
            model_name='hole',
            name='hole_size',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Size of the hole (1-10)'),
        ),
        migrations.AlterField(
            model_name='hole',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 16, 23, 54, 888848, tzinfo=utc), verbose_name='Submit Date'),
        ),
    ]
