# Generated by Django 3.2.10 on 2021-12-18 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PHTRS', '0006_hole_reporter_alter_hole_hole_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hole',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 12, 14, 47, 959347, tzinfo=utc), verbose_name='Submit Date'),
        ),
    ]
